offset_test:offset_test.o
	    g++ -g -o offset_test offset_test.o
offset_test.o:offset_test.c
	    g++ -g -c offset_test.c
container_test:container_test.o
	    g++ -g -o container_test container_test.o
container_test.o:container_test.c
	    g++ -g -c container_test.c
clean:all
	    rm all
